### PR TITLE
Lepatrick714/typeahead

### PR DESCRIPTION
**Pull request by lepatrick714**
Completed. UI is ugly but this new feature is required for production 1.0

Some screenshots: 
screen shot 2018-03-12 at 9 01 22 am

### CODE REVIEW

**Review by gprice1129 — DISMISSED** [review]

**Comment by kkong006** [comment]
Can you make the background white?

**Comment by kkong006** [comment]
Can you change the interval for the typeahead search to like 5 characters? We are going to run out of 1,000 API calls quickly if it's every 2 characters.

**Comment by lepatrick714** [comment]
screen shot 2018-03-12 at 9 50 35 am

**Comment by kkong006** [comment]
Why is the search bar where you're typing white instead of orange?

**Review by kkong006 — APPROVED** [review]
Looks legit

**Pull request merged**
