### PR TITLE
Playback speed

### PR DESCRIPTION
**Pull request by kkong006**
Change Log:
- Add Dialog Fragment to PlayerFragment to change playback speed
- Add API client methods to get and set playback speed
- Add session methods to get and set playback speed
- Add custom action to PlayerService to change playback speed

### CODE REVIEW

**Comment by ttony678** [comment]
Currently getting: 
JsonHttpRH: onFailure(int, Header[], String, Throwable) was not overriden, but callback was received
z.msebera.android.httpclient.client.HttpResponseException: NOT FOUND

Whenever I try to change the playback speed. The speed defaults back to 1x afterwards.

**Comment by kkong006** [comment]
@ttony678 The backend is not responding because the server doesn't have the endpoints. Please run the backend PlaybackSpeed branch locally or on the server.

**Comment by kkong006** [comment]
I'm considering letting the user change playback speed without waiting for a server response. The app will seem more responsive that way.

**Comment by lepatrick714** [comment]
@kkong006 I agree with your last comment. It's not the absolute proroity to save the user's playback speed right away. Reviewing both front and back ends right now.

**Review by ttony678 — APPROVED** [review]
Tested and working well when both programs are on the PlaybackSpeed branch

**Review by mschaffrath — APPROVED** [review]
Approved.

**Review by lepatrick714 — APPROVED** [review]
Solid Code Quality

**Pull request merged**
